[package]
name = "taiji_validator_node_rpc"
authors = ["OnSight Tech Services LLC"]
description = "This crate is to provide a single source for all cross application grpc files and conversions to and from taiji-dan applications"
repository = "https://github.com/onsight-tech-services/taiji-dan"
license = "BSD-3-Clause"
version = "0.50.0-pre.0"
edition = "2021"

[dependencies]
taiji_common_types = { git = "https://github.com/onsight-tech-services/taiji.git", branch = "taiji-feature-dan2" }
taiji_comms = { git = "https://github.com/onsight-tech-services/taiji.git", branch = "taiji-feature-dan2" }
taiji_comms_rpc_macros = { git = "https://github.com/onsight-tech-services/taiji.git", branch = "taiji-feature-dan2" }
tari_crypto = "0.18"

taiji_consensus = { path = "../consensus" }
taiji_dan_common_types = { path = "../common_types" }
taiji_dan_p2p = { path = "../p2p" }
taiji_dan_storage = { path = "../storage" }
taiji_engine_types = { path = "../engine_types" }
taiji_template_lib = { path = "../template_lib" }
taiji_transaction = { path = "../transaction" }
taiji_bor = { path = "../taiji_bor" }

anyhow = "1.0.53"
async-trait = "0.1"
chrono = "0.4.22"
log = "0.4"
prost = "0.9"
serde = "1.0"
thiserror = "1.0"
tokio-stream = "0.1"

[build-dependencies]
taiji_common = { git = "https://github.com/onsight-tech-services/taiji.git", branch = "taiji-feature-dan2", package = "taiji_common", features = ["build"] }

[package.metadata.cargo-machete]
ignored = [
    # Used via OUT_DIR macro, not detectable
    "prost",
]
