[package]
name = "taiji_dan_wallet_sdk"
authors = ["OnSight Tech Services LLC"]
description = "The Taiji DAN wallet library"
repository = "https://github.com/onsight-tech-services/taiji-dan"
version = "0.0.1"
edition = "2021"
license = "BSD-3-Clause"

[dependencies]
taiji_common_types = { git = "https://github.com/onsight-tech-services/taiji.git", branch = "taiji-feature-dan2" }
tari_crypto = { version = "0.18", features = ["borsh"] }
taiji_engine_types = { path = "../../engine_types" }
taiji_dan_common_types = { path = "../../common_types" }
# Just used for QuorumCertificate
taiji_dan_storage = { path = "../../storage" }
taiji_key_manager = { git = "https://github.com/onsight-tech-services/taiji.git", branch = "taiji-feature-dan2" }
taiji_transaction = { path = "../../transaction" }
taiji_template_lib = { path = "../../template_lib" }
tari_utilities = "0.4.10"

anyhow = "1.0"
async-trait = "0.1"
chacha20poly1305 = "0.10.1"
blake2 = "0.10.6"
digest = "0.10"
jsonwebtoken = "8.3.0"
lazy_static = "1.4.0"
log = "0.4.14"
rand = "0.8"
serde = "1.0.126"
serde_json = "1.0"
thiserror = "1.0.38"
zeroize = "1"

[dev-dependencies]
taiji_dan_wallet_storage_sqlite = { path = "../storage_sqlite" }

tempfile = "3.4.0"
